### ISSUE TITLE
"Check users for spam"  button work differently

### ISSUE THREAD

**Issue by Alexufo** [CleanTalk/phpbb3.1-3.2-antispam#25]
This button work very strange.
All users in result are real users.

In main_listener.php
    if(sizeof($users[$cnt])>450) - this change array shift depends on user counts?
 change 450 to 800 and result of "spam" will be less. Change to 300 - and "spam" accounts will be more.

**Comment by VladCleantalk** [comment]
Hello!
Please, give us emails of real users, that marked as spam by this checking. Send it to my email: gorbatov at cleantalk dot org
