### ISSUE TITLE
Страница настройки расширения крэшится в версии 5.4 при использовании posqtgresql

### ISSUE THREAD

**Issue by 1-bit** [CleanTalk/phpbb3.1-3.2-antispam#49]
Привет!

После обновления плагина до версии 5.4, страница с настройками расширения крэшится при формировании постраничного списка пользователей из-за неподдерживаемого синтаксиса (LIMIT [offset,] row_count) при использовании postgresql.

**Comment by ardavydov** [comment]
Здравствуйте,

Будет исправлено в следующей версии. Релиз ожидается на этой неделе.

https://github.com/CleanTalk/phpbb3.1-3.2-antispam/blob/4131c61353b417ab935bacc18f81902731bac74c/cleantalk/antispam/acp/main_module.php#L263
