### ISSUE TITLE
Ошибка при добавлении ключа доступа в настройках расширения.  

### ISSUE THREAD

**Issue by 1-bit** [CleanTalk/phpbb3.1-3.2-antispam#50]
Привет! 

При добавлении ключа доступа в настройках расширения вылетает исключение: 

Uncaught Error: Class 'cleantalk\antispam\acp\CleantalkHelper' not found in /var/www/forum/ext/cleantalk/antispam/acp/main_module.php:70

Аналогично для кнопки "проверить на спам" - Uncaught Error: Class 'cleantalk\antispam\acp\CleantalkHelper' not found in /var/www/forum/ext/cleantalk/antispam/acp/main_module.php:202

Версия 5.5

**Comment by ardavydov** [comment]
Добрый день.

Исправлено в текущей версии
