### ISSUE TITLE
The "Check users for spam" in ACP has weird behavior.

### ISSUE THREAD

**Issue by Dark1z** [CleanTalk/phpbb3.1-3.2-antispam#55]
The "Check users for spam" button in ACP has weird behavior,    
The line 
https://github.com/CleanTalk/phpbb3.1-3.2-antispam/blob/b01177f18a87b2b3b30b40dc1a5d6c597f564394/cleantalk/antispam/acp/main_module.php#L247
in `./ext/cleantalk/antispam/acp/main_module.php` ,    
If I change the value `450` to `200` the list is reduced to almost half.
so on for `100`, `50`, `10` & just 3 when it's `1`.   

Why is this Happening ?
is the code in `main_module.php` **OR** is there something wrong in CleanTalk API ???

Should not the list be consistent across different values in that line... ???

PS: this is kind of duplicate of https://github.com/CleanTalk/phpbb3.1-3.2-antispam/issues/25 but it's closed now...

Best regards 👍

**Comment by dark-1** [comment]
PS: this is kind of duplicate of https://github.com/CleanTalk/phpbb3.1-3.2-antispam/issues/25
but it's closed now...

**Comment by ardavydov** [comment]
Hello @dark-1 

Thanks, it's a plugin issue and as i know, it was a temporary fix to avoid some limit of users. Anyway, we need to optimise this spam check table now.

As for your previous commit about "Clear list" button, please make a pull request again and explain why do you need this button there? 

Best regards.

**Comment by Dark1z** [comment]
@davydovct ,

Ok...

About "Clear list" button ,
It's somewhat related to this bug , but also can be a feature.

I wanted something that will clear the flag from user_table coz there were plenty of False_Positive.
So another admin do not delete a valid user thinking it as "Spam user", to prevent that clear the flag from all users.

If this Bug is fixed , it can be a feature for Admin to clean the list and let the page load faster.

I prefer that you do the required changes to realize this "Clear list" button.

One more thing , should I add directly the `.gitattributes` file ???
That will keep some consistency across repo.

Best regards 👍
