### ISSUE TITLE
"Check users for spam" feature needs selective whitelisting/greylisting, or a "Delete all who has 0 posts" feature

### ISSUE THREAD

**Issue by mdrejhon** [CleanTalk/phpbb3.1-3.2-antispam#57]
Paying CleanTalk user here.

I discovered a huge list of mainly 0-post spam users found on my forums -- and I need to delete all of them.

But I can't use "Delete all" because 3 of them have what are extremely useful posts (not found elsewhere; not copy pastes; actual direct replies) that were clearly human-written in a relevant way and not bot-written.   I want to preserve those posts that have been sitting there for some time now.  Even if I delete these users, I want to keep these specific posts. 

In a case, **One of the email addresses is a long-dormant member hacked by a spammer so it only got blacklisted later; which means the original email address owner had many legitimate posts at first**...  So I don't want to delete all of their posts;

My option is to delete 1000+ spam users one by one, because the "Delete All" will remove the few non-spam posts I want to keep. 

Almost all my obvious spam users are 0 posts, so perhaps a compromise is a "**Delete all who has 0 posts**" selection feature.  

That way I can _manually administer_ the remaining suspicious users who have nonzero posts (e.g. delete/ban while keeping certain posts).

Thank you!

![image](https://user-images.githubusercontent.com/59981975/100494719-54fd7080-3112-11eb-9d69-8962495c5064.png)

Also would be helpful to have a chekbox at the top-left for "Select/Unselect All On This Screen"

![image](https://user-images.githubusercontent.com/59981975/100494757-be7d7f00-3112-11eb-929e-e4eeff4b522d.png)

**Comment by ardavydov** [comment]
Hello,
Unfortunately, due to high load we don't plan to add this feature at this moment. You can try to add this feature by yourself and make a pull request to this repo. We will review it and accept if everything is fine.
