### ISSUE TITLE
Data too long for column 'config_value'

### ISSUE THREAD

**Issue by vanwinssen** [CleanTalk/phpbb3.1-3.2-antispam#61]
Hi,

After upgrading from an earlier version, I now use the latest version 5.7.5 of this extension on a PHPBB 3.3.9 forum.
At some point in using our forum (e.g. register a new user, or using our contact form) I get an error "Data too long for column 'config_value'" that seems to be related to this line of code:

https://github.com/CleanTalk/phpbb3.1-3.2-antispam/blob/1be64394fe877a3ba4c8f02cefd013ad3c2d604d/cleantalk/antispam/model/main_model.php#L555

The data exceeds the length of the column "config_value" in the table "phpbb_config", which is of type varchar(255).

I think the data should be better stored in the other table "phpbb_config_text", so the 255-limit doesn't apply on this type of information that the extension is trying to store?

Thanks!

**Comment by svfcode** [comment]
Hello, thank you for contacting us. Changes in the latest release.
